web-后端/下半部/web17/web15上课用品/models/blog.py
import time
from models import Model

# 针对我们的数据 comment
# 我们要做 4 件事情
"""
C create 创建数据
R read 读取数据
U update 更新数据
D delete 删除数据

Comment.new() 来创建一个 todo
"""


class Blog(Model):
    @classmethod
    def new(cls, form):
        """
        创建并保存一个 todo 并且返回它
        Todo.new({'title': '吃饭'})
        :param form: 一个字典 包含了 todo 的数据
        :return: 创建的 todo 实例
        """
        # 下面一行相当于 t = Todo(form)
        t = cls(form)
        t.save()
        return t

    def __init__(self, form):
        self.id = None
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.author = form.get('author', '')
        self.create_time = int(time.time())


class BlogComment(Model):
    @classmethod
    def new(cls, form):
        """
        创建并保存一个 todo 并且返回它
        Todo.new({'title': '吃饭'})
        :param form: 一个字典 包含了 todo 的数据
        :return: 创建的 todo 实例
        """
        # 下面一行相当于 t = Todo(form)
        t = cls(form)
        t.save()
        return t

    def __init__(self, form):
        self.id = None
        self.content = form.get('content', '')
        self.author = form.get('author', '')
        self.blog_id = int(form.get('blog_id', 0))
        self.create_time = int(time.time())

web-后端/下半部/web17/web15上课用品/models/comment.py
import time
from models import Model

# 针对我们的数据 comment
# 我们要做 4 件事情
"""
C create 创建数据
R read 读取数据
U update 更新数据
D delete 删除数据

Comment.new() 来创建一个 todo
"""


class Comment(Model):
    @classmethod
    def new(cls, form):
        """
        创建并保存一个 todo 并且返回它
        Todo.new({'title': '吃饭'})
        :param form: 一个字典 包含了 todo 的数据
        :return: 创建的 todo 实例
        """
        # 下面一行相当于 t = Todo(form)
        t = cls(form)
        t.save()
        return t

    def __init__(self, form):
        self.id = None
        self.content = form.get('content', '')
        self.author = form.get('author', '')
        self.create_time = int(time.time())

web-后端/下半部/web17/web15上课用品/routes/blog.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
# 一次性引入多个 flask 里面的名字
# 注意最后一个后面也应该加上逗号
# 这样的好处是方便和一致性

from models.blog import (
    Blog,
    BlogComment,
)
from utils import log

# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字, 以后会有用(add函数里面就用到了)
# 第二个参数是套路
main = Blueprint('blog', __name__)


@main.route("/")
def index():
    all_blog = Blog.all()
    return render_template("blog_index.html", blogs=all_blog)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    Blog.new(form)
    return redirect(url_for('.index'))


@main.route("/new", methods=["GET"])
def new():
    return render_template("blog_new.html")


@main.route("/<int:blog_id>", methods=["GET"])
def view(blog_id):
    comments = BlogComment.find_all(blog_id=blog_id)
    blog = Blog.find(blog_id)
    return render_template("blog_view.html", blog=blog, comments=comments)


@main.route("/comment/new", methods=["POST"])
def comment():
    form = request.form
    BlogComment.new(form)
    return redirect(url_for('.view', blog_id=form.get("blog_id")))

web-后端/下半部/web17/web15上课用品/routes/comment.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
# 一次性引入多个 flask 里面的名字
# 注意最后一个后面也应该加上逗号
# 这样的好处是方便和一致性

from models.comment import Comment
from utils import log

# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字, 以后会有用(add函数里面就用到了)
# 第二个参数是套路
main = Blueprint('comment', __name__)

@main.route('/')
def index():
    comments = Comment.all()
    return render_template('comment.html', comments = comments)

# http://localhost:2000/todo/add?a=b&c
# request.args
# dict
#
'''
{
    'a' : 'b',
    'c' : ''

}'''

'''
HTTP/1.0 302 FOUND
Content-Type: text/html; charset=utf-8
Content-Length: 219
Location: http://localhost:2000/todo/
'''
# /todo/add only post
@main.route('/add', methods=['POST'])
def add():
    t = Comment.new(request.form)
    t.save()
    # 蓝图中的 url_for 需要加上蓝图的名字，这里是 todo

    # todo.index blueprint
    # todo.index
    # /todo/
    return redirect(url_for('.index'))


# /todo/delete/1
# /todo/delete/2
'''
GET /todo/delete/2/ HTTP/1.1
Host: localhost:2000
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: http://localhost:2000/todo/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4
'''
# 动态路由
@main.route('/delete/<int:todo_id>/')
def delete(todo_id):
    """
    <int:todo_id> 的方式可以匹配一个 int 类型
    int 指定了它的类型，省略的话参数中的 todo_id 就是 str 类型

    这个概念叫做 动态路由
    意思是这个路由函数可以匹配一系列不同的路由

    动态路由是现在流行的路由设计方案
    """
    # 通过 id 删除 todo
    t = Todo.delete(todo_id)
    log("deleted todo id", todo_id)
    # 引用蓝图内部的路由函数的时候，可以省略名字只用 .
    # 因为我们就在 todo 这个蓝图里面, 所以可以省略 todo
    # return redirect(url_for('todo.index'))
    return redirect(url_for('.index'))

web-后端/下半部/web17/web15上课用品/routes/todo.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)
# 一次性引入多个 flask 里面的名字
# 注意最后一个后面也应该加上逗号
# 这样的好处是方便和一致性

from models.todo import Todo
from utils import log

# 创建一个 蓝图对象 并且路由定义在蓝图对象中
# 然后在 flask 主代码中「注册蓝图」来使用
# 第一个参数是蓝图的名字, 以后会有用(add函数里面就用到了)
# 第二个参数是套路
main = Blueprint('todo', __name__)

'''
GET /todo/ HTTP/1.1
Host: localhost:2000
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4
'''

'''
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 1734
Server: Werkzeug/0.12.1 Python/3.6.0
Date: Fri, 17 Mar 2017 13:05:19 GMT'''
# /todo/
@main.route('/')
def index():
    # 查找所有的 todo 并返回
    todo_list = Todo.all()
    request.method
    log("args", request.args)
    # []
    # todos = todolist
    # flask 已经配置好了 jinja2 模板引擎
    # 并且可以直接使用 render_template 来生成响应数据(http_response)
    return render_template('todo_index.html', todos=todo_list)

# http://localhost:2000/todo/add?a=b&c
# request.args
# dict
#
'''
{
    'a' : 'b',
    'c' : ''

}'''

'''
HTTP/1.0 302 FOUND
Content-Type: text/html; charset=utf-8
Content-Length: 219
Location: http://localhost:2000/todo/
'''
# /todo/add only post
@main.route('/add', methods=['POST', 'GET'])
def add():
    if request.method == 'GET':
        return redirect(url_for('todo.index'))
    # request local
    # post form request.form()
    # get request.args
    form = request.form
    t = Todo.new(form)
    t.save()
    # 蓝图中的 url_for 需要加上蓝图的名字，这里是 todo

    # todo.index blueprint
    # todo.index
    # /todo/
    return redirect(url_for('todo.index'))


# /todo/delete/1
# /todo/delete/2
'''
GET /todo/delete/2/ HTTP/1.1
Host: localhost:2000
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: http://localhost:2000/todo/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4
'''
# 动态路由
@main.route('/delete/<int:todo_id>/')
def delete(todo_id):
    """
    <int:todo_id> 的方式可以匹配一个 int 类型
    int 指定了它的类型，省略的话参数中的 todo_id 就是 str 类型

    这个概念叫做 动态路由
    意思是这个路由函数可以匹配一系列不同的路由

    动态路由是现在流行的路由设计方案
    """
    # 通过 id 删除 todo
    t = Todo.delete(todo_id)
    log("deleted todo id", todo_id)
    # 引用蓝图内部的路由函数的时候，可以省略名字只用 .
    # 因为我们就在 todo 这个蓝图里面, 所以可以省略 todo
    # return redirect(url_for('todo.index'))
    return redirect(url_for('.index'))

web-后端/下半部/web17/web15上课用品/templates/blog_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客主页</title>
</head>
<body>
<a href={{ url_for(".new") }}>新建博客</a>
<div>
    {% for b in blogs %}
        <div>
        <a href= {{ url_for(".view", blog_id=b.id) }}>
        {{ b.title }} @ {{ b.create_time }} by {{ b.author }}
        </a>
        </div>
    {% endfor %}
</div>

</body>
</html>

web-后端/下半部/web17/web15上课用品/templates/blog_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发表新博文</title>
</head>
<body>
<form method="POST" action={{ url_for(".add") }}>
    <input type="text" name="author" placeholder="author">
    <input type="text" name="title" placeholder="title">
    <br>
    <textarea name = "content" placeholder="content">
    </textarea>
    <br>
    <button type="submit">发布</button>
</form>

</body>
</html>

web-后端/下半部/web17/web15上课用品/templates/blog_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>
</head>
<h1>{{ blog.title }}</h1>
<h3>{{ blog.author }}</h3>
<p>{{ blog.content }}</p>

<form method="post" action="comment/new">
    <input type="text" name="author" placeholder="author">
    <input type="text" name="content" placeholder="content">
    <input type="hidden" name="blog_id" value={{ blog.id }}>
    <button type="submit">提交评论</button>
</form>

<div>
    {% for c in comments %}
        <div>{{ c.content }} @ {{ c.author }}</div>
    {% endfor %}
</div>
<body>

</body>
</html>

web-后端/下半部/web17/web15上课用品/templates/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="//cdn.bootcss.com/bootstrap/4.0.0-alpha.6/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<form method="post" action="/comment/add">
    <input class="form-control" type="text" name="content" placeholder="comment">
    <input class="form-control" type="text" name="author" placeholder="author">
    <button class="btn btn-default" type="submit">提交留言</button>
</form>

<div>
    {% for c in comments %}
    <div class="bg-success">
        {{ c.content }} for {{ c.author }} @ {{ c.create_time }}
    </div>
    {% endfor %}
</div>

</body>
</html>

web-后端/下半部/web17/web15上课用品/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
</head>
<body>
    <h1>{{ user }}</h1>
    <h2>
        <a href="{{ url_for('.profile') }}">个人资料页面</a>
    </h2>
    <form method="post" action="{{ url_for('.register') }}">
        <input name="username">
        <br>
        <input name="password">
        <br>
        <button type="submit">注册</button>
    </form>
    <form method="post" action="{{ url_for('.login') }}">
        <input name="username">
        <br>
        <input name="password">
        <br>
        <button type="submit">登录</button>
    </form>
</body>
</html>

web-后端/下半部/web17/web15上课用品/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

web-后端/下半部/web17/web15上课用品/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
    <h1>用户资料页面</h1>
    <div>
        {{ user.id }}
    </div>
    <div>
        {{ user.name }}
    </div>
    <div>
        {{ user.password }}
    </div>
</body>
</html>

web-后端/下半部/web17/web15上课用品/templates/session_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> hello {{ username }}!</p>
<form method="get" action={{ url_for(".log_out") }}>
    <button type="submit">退出登录</button>
</form>
</body>
</html>

web-后端/下半部/web17/web15上课用品/templates/todo_index.html
<html>
<head>
    <title>Todo</title>
    <!-- 静态文件放在 /static 文件夹中 -->
    <!-- 引用路径是 /static/... -->
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <style type="text/css">
    .todo-table {
        margin: 0 auto;
    }
    .center {
        text-align: center;
    }
    </style>
</head>

<body>
    <div class="center">
        <h1>Todo</h1>
        <!-- 注意这里 的 url_for 也是需要加上蓝图名字前缀的 -->
        <!-- action /todo/add-->
        <form action={{ url_for("todo.add") }} method="post">
            <input type="text" placeholder="Add Todo" name="title">
            <input class="pure-button pure-button-primary" type="submit" value="Add">
        </form>
    </div>

    <table class="todo-table pure-table pure-table-horizontal pure-table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Time</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for t in todos %}
            <tr>
                <td>{{ t.id }}</td>
                <td>{{ t.title }}</td>
                <td>{{ t.ct }}</td>
                <!-- url_for 可以传递参数，先匹配动态路由，如果动态路由匹配失败则变成 query 参数 -->
                <td><a href={{ url_for('.delete', todo_id=t.id) }}>delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</body>
</html>